"""Registry client: create service identities, upsert ACL rules, wait for health.

Replaces ``bootstrap/svc-init.sh``'s identity-creation curl call (step 6) and the
deployer's ``registry.py`` applier (``components/deployer/src/deployer/appliers/
registry.py``) with one stdlib client the sync loop (T3.1) drives.

**Wire contract** (read from the registry source, not guessed):

``POST {base_url}/api/services``
    ``registry/api/services.py:236`` (``router = APIRouter(prefix="/api/services")``
    at line 21). Creates a brand-new service identity; admin-gated via
    ``Depends(require_admin_or_token)`` (``registry/auth_dep.py:146``, accepting
    ``X-Admin-Token`` by HMAC compare, or an admin JWT/PAT/cookie — this client
    only ever uses the token). The header ``X-Service-Secret`` (required, line
    240) becomes the credential the service itself later re-registers with; it
    is never generated by the registry, so the caller supplies it. Request body
    is ``RegisterRequest`` (line 109): this client sends ``id``, ``audience``,
    ``display_name``, ``owner``, ``capabilities`` — the fields ``registry.json``
    (``docs/platform-sidecars.md``) carries. ``health_path`` is accepted by this
    client's ``create_identity`` for symmetry with the sidecar and is validated,
    but ``RegisterRequest`` has no such field, so it is deliberately NOT put on
    the wire; the sync loop uses it locally for the ams declaration's
    ``[health]`` block and for composing the URL it passes to ``wait_healthy``.
    ``201`` = created. ``409`` (line 259/318, id already exists) is success with
    nothing changed — mirrors ``svc-init.sh``'s "idempotent: HTTP 409 is treated
    as success" (``bootstrap/svc-init.sh``, step 6 comment). Any other 4xx (401/
    403 bad admin auth, 422 bad payload) is not retried. 502/503/504 are retried
    (a trust-root redeploy restarting the registry, same rationale as the
    deployer's applier docstring).

``POST {base_url}/api/acl``
    ``registry/api/acl.py:52``, under prefix ``/api/acl`` (line 26). Upserts one
    ACL rule; admin-gated the same way (``require_admin_or_token``, no service
    secret involved — unlike identity creation). Body is ``ACLRule`` (line 33):
    ``service_id``, ``action``, ``principal``, ``effect`` (default ``"allow"``,
    filled in here so the wire body always carries it explicitly). One POST per
    rule, exactly like the deployer's ``_upsert_acl`` in
    ``components/deployer/src/deployer/appliers/registry.py`` — that function is
    also this module's source for the retry policy below.

``GET {base_url}/health``
    ``registry/api/health.py:21``. Unauthenticated, returns
    ``{"status": "ok", "services_count": N}`` on success. Used by
    :meth:`RegistryClient.wait_healthy` as a readiness gate; any non-200 (or a
    transport error) means "not yet".

**Retry policy**: 502/503/504 only, on the same backoff schedule as the
deployer's applier — ``RETRY_DELAYS = (1, 2, 4, 8, 15, 30, 60, 60, 60)`` seconds
(``components/deployer/src/deployer/appliers/registry.py``, module-level
``RETRY_DELAYS``) — chosen there to outlast a trust-root redeploy's worst
observed case (~3 min). A network-level failure (``URLError``, connection
refused, timeout) is treated the same as a 502/503/504: the registry restarting
looks identical to the caller whether or not it currently accepts a TCP
connection. Any other 4xx status is raised immediately, no retry — retrying a
bad token or a malformed payload would only mask the real error (same reasoning
as the deployer applier's docstring).

**Phase-A safety guard**: ``base_url`` must be ``http://127.0.0.1:<port>`` or
``http://localhost:<port>`` (D18 / PLAN-allin.md risk 5: an auto-generated
``SVC_SECRET`` and identity creation must never be able to reach production on
a wrong ``REGISTRY_URL``). Anything else raises :class:`RegistryError` before
any network call is made.

**Secrets never leak**: the service secret (a call argument, never stored) and
the admin token (wrapped in :class:`_Redacted`, stored on the client) appear in
neither a log record nor an exception message nor ``repr()``/``str()`` of the
client. Every call logs INFO with method, path, HTTP status and attempt number
only — never a header or a request/response body.
"""

from __future__ import annotations

import json
import logging
import re
import time
import urllib.error
import urllib.request
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from typing import Any

log = logging.getLogger("ams.platform.registryclient")

#: Same schedule as the deployer's registry applier
#: (``components/deployer/src/deployer/appliers/registry.py``, ``RETRY_DELAYS``):
#: must outlast a trust-root redeploy's worst observed case (~3 min).
RETRY_DELAYS: tuple[float, ...] = (1, 2, 4, 8, 15, 30, 60, 60, 60)

#: Only these statuses are retried — a restarting registry, nothing else
#: (``deployer/appliers/registry.py``, ``RETRYABLE_STATUSES``).
RETRYABLE_STATUSES = frozenset({502, 503, 504})

DEFAULT_HEALTH_PATH = "/health"

# Mirrors registry's ID_PATTERN (registry/api/services.py:23) — the same
# regex the server itself enforces on `id` and `audience`, checked here too so
# a malformed id fails fast with a clear message instead of a 422 round trip.
_ID_RE = re.compile(r"^[a-z][a-z0-9-]*$")
_MAX_ID_LEN = 64

# http://127.0.0.1:<port> or http://localhost:<port> only — see module
# docstring, "Phase-A safety guard".
_LOOPBACK_BASE_RE = re.compile(r"^http://(127\.0\.0\.1|localhost):([1-9][0-9]{0,4})$")


class RegistryError(RuntimeError):
    """A registry call failed, was refused before it ran, or exhausted retries.

    The message never carries a secret or the admin token — see the module
    docstring's "Secrets never leak".
    """


class _TransportError(Exception):
    """Internal: a network-level failure, handled like a 502/503/504."""


class _Redacted:
    """Wraps a token so an accidental ``str()``/``repr()``/f-string never reveals it.

    ``reveal()`` is the only way to get the raw value back out, and it is
    called in exactly one place: building the outgoing header dict.
    """

    __slots__ = ("_value",)

    def __init__(self, value: str) -> None:
        if not isinstance(value, str) or not value:
            raise RegistryError("token must be a non-empty string")
        self._value = value

    def reveal(self) -> str:
        return self._value

    def __repr__(self) -> str:  # pragma: no cover - trivial
        return "_Redacted(***)"

    def __str__(self) -> str:  # pragma: no cover - trivial
        return "***"


@dataclass(frozen=True, slots=True)
class IdentityResult:
    """Outcome of :meth:`RegistryClient.create_identity`.

    ``created=True`` means a brand-new identity was made (HTTP 201).
    ``created=False`` means the id already existed (HTTP 409) — also success,
    nothing was changed (mirrors ``svc-init.sh``'s idempotent re-run).
    """

    created: bool


def _validate_id(value: str, field: str) -> str:
    if not isinstance(value, str) or not value or len(value) > _MAX_ID_LEN:
        raise RegistryError(
            f"invalid {field} {value!r}: must be 1-{_MAX_ID_LEN} chars matching "
            "^[a-z][a-z0-9-]*$"
        )
    if not _ID_RE.match(value):
        raise RegistryError(f"invalid {field} {value!r}: must match ^[a-z][a-z0-9-]*$")
    return value


def _validate_base_url(base_url: str) -> str:
    normalized = base_url.rstrip("/")
    m = _LOOPBACK_BASE_RE.match(normalized)
    if not m or int(m.group(2)) > 65535:
        raise RegistryError(
            f"refusing non-loopback registry base_url {base_url!r} in Phase A: "
            "only http://127.0.0.1:<port> or http://localhost:<port> is allowed "
            "(PLAN-allin.md risk 5 — SVC_SECRET/identity creation must never "
            "reach production on a wrong REGISTRY_URL)"
        )
    return normalized


def _safe_text(data: bytes, limit: int = 2000) -> str:
    text = data.decode("utf-8", errors="replace")
    return text if len(text) <= limit else text[:limit] + "...(truncated)"


class RegistryClient:
    """Talks to a Phase-A (loopback-only) registry instance over ``urllib``."""

    def __init__(
        self,
        base_url: str,
        admin_token: str,
        timeout_s: float = 10.0,
        *,
        sleep_fn: Callable[[float], None] = time.sleep,
        now_fn: Callable[[], float] = time.monotonic,
    ) -> None:
        self._base_url = _validate_base_url(base_url)
        self._admin_token = _Redacted(admin_token)
        self._timeout_s = timeout_s
        self._sleep = sleep_fn
        self._now = now_fn

    def __repr__(self) -> str:
        return f"RegistryClient(base_url={self._base_url!r}, admin_token=***)"

    # ------------------------------------------------------------------ http

    def _url(self, path: str) -> str:
        return f"{self._base_url}{path}"

    def _do_request(
        self, method: str, url: str, *, headers: Mapping[str, str], body: bytes | None
    ) -> tuple[int, bytes]:
        req = urllib.request.Request(url, data=body, headers=dict(headers), method=method)
        try:
            with urllib.request.urlopen(req, timeout=self._timeout_s) as resp:  # noqa: S310
                return resp.status, resp.read()
        except urllib.error.HTTPError as e:
            return e.code, e.read()
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            raise _TransportError(str(e)) from e

    def _request_with_retry(
        self,
        method: str,
        path: str,
        *,
        headers: Mapping[str, str],
        body: bytes | None,
        what: str,
        extra_success_statuses: frozenset[int] = frozenset(),
    ) -> tuple[int, bytes]:
        url = self._url(path)
        attempts = len(RETRY_DELAYS) + 1
        last_detail = ""
        for attempt in range(1, attempts + 1):
            try:
                status, data = self._do_request(method, url, headers=headers, body=body)
            except _TransportError as e:
                last_detail = f"transport error: {e}"
                log.warning(
                    "%s: %s %s -> transport error attempt=%d/%d",
                    what,
                    method,
                    path,
                    attempt,
                    attempts,
                )
            else:
                log.info("%s: %s %s -> status=%d attempt=%d", what, method, path, status, attempt)
                if status < 400 or status in extra_success_statuses:
                    return status, data
                if status not in RETRYABLE_STATUSES:
                    raise RegistryError(
                        f"{what} failed: HTTP {status} {_safe_text(data)}"
                    )
                last_detail = f"HTTP {status} {_safe_text(data)}"

            if attempt <= len(RETRY_DELAYS):
                delay = RETRY_DELAYS[attempt - 1]
                log.warning(
                    "%s: transient failure (%s); retry %d/%d in %.0fs",
                    what,
                    last_detail,
                    attempt,
                    len(RETRY_DELAYS),
                    delay,
                )
                self._sleep(delay)

        raise RegistryError(
            f"{what} failed after {attempts} attempts (~{sum(RETRY_DELAYS):.0f}s): {last_detail}"
        )

    # -------------------------------------------------------------- identity

    def create_identity(
        self,
        service_id: str,
        secret: str,
        *,
        audience: str,
        display_name: str | None = None,
        owner: str | None = None,
        capabilities: Iterable[str] = (),
        health_path: str = DEFAULT_HEALTH_PATH,
    ) -> IdentityResult:
        """``POST /api/services``. 409 (already exists) is success, not an error.

        ``health_path`` is validated but never put on the wire — see the module
        docstring for why (``RegisterRequest`` has no such field).
        """
        _validate_id(service_id, "service_id")
        _validate_id(audience, "audience")
        if not isinstance(health_path, str) or not health_path.startswith("/"):
            raise RegistryError(f"health_path must start with '/': {health_path!r}")
        if not isinstance(secret, str) or not secret:
            raise RegistryError("secret must be a non-empty string")

        body = json.dumps(
            {
                "id": service_id,
                "audience": audience,
                "display_name": display_name,
                "owner": owner,
                "capabilities": list(capabilities),
            }
        ).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "X-Service-Secret": secret,
            "X-Admin-Token": self._admin_token.reveal(),
        }
        status, _data = self._request_with_retry(
            "POST",
            "/api/services",
            headers=headers,
            body=body,
            what=f"create identity {service_id!r}",
            extra_success_statuses=frozenset({409}),
        )
        return IdentityResult(created=status < 400)

    # ------------------------------------------------------------------- acl

    def upsert_acl(self, service_id: str, rules: Iterable[Mapping[str, Any]]) -> None:
        """``POST /api/acl`` once per rule. ``effect`` defaults to ``"allow"``."""
        _validate_id(service_id, "service_id")
        headers = {
            "Content-Type": "application/json",
            "X-Admin-Token": self._admin_token.reveal(),
        }
        for rule in rules:
            action = rule["action"]
            principal = rule["principal"]
            effect = rule.get("effect", "allow")
            body = json.dumps(
                {
                    "service_id": service_id,
                    "action": action,
                    "principal": principal,
                    "effect": effect,
                }
            ).encode("utf-8")
            self._request_with_retry(
                "POST",
                "/api/acl",
                headers=headers,
                body=body,
                what=f"acl upsert {action}/{principal} on {service_id}",
            )

    # ---------------------------------------------------------------- health

    def wait_healthy(self, url: str, deadline_s: float, interval_s: float = 1.0) -> bool:
        """GET ``url`` until it returns 200 or ``deadline_s`` elapses.

        A transport error counts as "not yet healthy", not a raised error —
        the registry may simply not be listening yet.
        """
        started = self._now()
        while True:
            try:
                status, _data = self._do_request("GET", url, headers={}, body=None)
            except _TransportError as e:
                status = None
                log.info("wait_healthy: GET %s -> transport error: %s", url, e)
            else:
                log.info("wait_healthy: GET %s -> status=%s", url, status)
            if status == 200:
                return True
            if self._now() - started >= deadline_s:
                return False
            self._sleep(interval_s)


def from_sidecar(reg: Mapping[str, Any]) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
    """Map a ``registry.json`` sidecar (``docs/platform-sidecars.md``) to call args.

    Returns ``(service_id, create_identity_kwargs, acl_rules)`` where
    ``create_identity_kwargs`` is ready to splat into
    :meth:`RegistryClient.create_identity` alongside the caller's own
    ``service_id`` and ``secret`` (the secret is never in the sidecar — D16 —
    the caller reads it from the SecretStore), and ``acl_rules`` is ready to
    pass straight to :meth:`RegistryClient.upsert_acl`.

    Raises :class:`RegistryError` if ``version`` is not the one shape this
    module understands (sidecar contract: "a consumer that reads a version it
    does not know must fail loudly rather than guess").
    """
    version = reg.get("version")
    if version != 1:
        raise RegistryError(f"unsupported registry.json version {version!r}; expected 1")
    service_id = reg["id"]
    kwargs: dict[str, Any] = {
        "audience": reg["audience"],
        "display_name": reg.get("display_name"),
        "owner": reg.get("owner"),
        "capabilities": list(reg.get("capabilities") or []),
        "health_path": reg.get("health_path", DEFAULT_HEALTH_PATH),
    }
    rules = list(reg.get("acl") or [])
    return service_id, kwargs, rules
