"""Service declaration schema.

A declaration is a TOML document generated by the agent (not hand-written by
the user) describing one supervised service. This module is the single source
of truth for what a declaration may contain; every other module consumes the
frozen dataclasses defined here and never re-parses TOML.

Design rules:
- Frozen dataclasses only. Declarations are immutable once loaded.
- Validation happens at load time and raises ``DeclError`` with a path-like
  message (``limits.memory_max: ...``) so the agent can repair the file.
- ``argv`` is a list, never a shell string. Log lines are attacker-influenced
  input that may end up in repair actions; we never hand them to a shell.
"""

from __future__ import annotations

import re
import signal
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field, fields
from pathlib import Path
from types import MappingProxyType
from typing import Any, Literal, Union, get_args, get_origin, get_type_hints

SERVICE_ID_RE = re.compile(r"^[a-z][a-z0-9-]{0,31}$")
PORT_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{0,15}$")
ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
# Set by the harness; a declaration may not override them (would desync the
# per-service runtime bin dir, the port the health probe uses, etc.).
RESERVED_ENV = frozenset({"PATH", "HOME", "LANG", "PYTHONUNBUFFERED", "VIRTUAL_ENV"})
RESERVED_ENV_PREFIXES = ("AMS_", "PORT_", "UV_", "PNPM_", "BUN_", "npm_config_")
_SIZE_RE = re.compile(r"^(\d+)([KMGT]?)$", re.IGNORECASE)
_PCT_RE = re.compile(r"^(\d+(?:\.\d+)?)%$")

RuntimeKind = Literal["none", "venv", "uv", "pnpm", "bun", "nix"]
HealthKind = Literal["none", "tcp", "http", "log"]
RestartPolicy = Literal["always", "on-failure", "never"]

# Ports below this are not bindable rootless; the allocator never hands them out.
MIN_PORT = 1024
MAX_PORT = 65535
# cpu.max period we always use; quota is derived from a percentage of one CPU.
CPU_PERIOD_US = 100_000


class DeclError(ValueError):
    """Invalid service declaration. Message is prefixed with the field path."""


def _err(path: str, msg: str) -> DeclError:
    return DeclError(f"{path}: {msg}")


@dataclass(frozen=True)
class StartSpec:
    argv: tuple[str, ...]
    # Relative to the service root (``<state>/services/<id>/root``) unless absolute.
    workdir: str = "."


@dataclass(frozen=True)
class RuntimeSpec:
    """Per-service dependency isolation. userns gives permission boundaries only."""

    kind: RuntimeKind = "none"
    python: str | None = None  # venv/uv: "3.12"; interpreter resolved by the provisioner
    node: str | None = None  # pnpm/bun: "22"; pnpm uses system/pnpm-managed node, bun ignores
    requirements: str | None = None  # venv/uv: path relative to workdir
    # uv only: workdir is a uv project (pyproject.toml + uv.lock); provision runs
    # `uv sync --frozen` there and the venv lives at <workdir>/.venv. Path
    # dependencies (e.g. ../../components/sdk) resolve relative to workdir.
    sync: bool = False
    packages: tuple[
        str, ...
    ] = ()  # pip/uv specs, or npm specs for pnpm/bun (added to package.json)
    nix_packages: tuple[str, ...] = ()  # nix profile packages (kind == "nix")

    @property
    def is_python(self) -> bool:
        return self.kind in ("venv", "uv")

    @property
    def is_node(self) -> bool:
        return self.kind in ("pnpm", "bun")


@dataclass(frozen=True)
class HealthSpec:
    kind: HealthKind = "none"
    port: str | None = None  # name in ``ports``; required for tcp/http
    path: str = "/"  # http only
    pattern: str | None = None  # log only: regex that marks the service ready
    interval_s: float = 10.0
    timeout_s: float = 5.0
    start_period_s: float = 30.0


@dataclass(frozen=True)
class StopSpec:
    signal: str = "SIGTERM"
    timeout_s: float = 10.0

    @property
    def signum(self) -> int:
        return int(getattr(signal, self.signal))


@dataclass(frozen=True)
class LimitsSpec:
    memory_max: str | None = None  # "256M"
    cpu_max: str | None = None  # "50%" of one CPU, may exceed 100%
    pids_max: int | None = None

    @property
    def memory_max_bytes(self) -> int | None:
        return parse_size(self.memory_max) if self.memory_max else None

    @property
    def cpu_max_value(self) -> str | None:
        """Value to write to cgroup ``cpu.max`` (``"<quota> <period>"``)."""
        if not self.cpu_max:
            return None
        pct = parse_percent(self.cpu_max)
        return f"{int(CPU_PERIOD_US * pct / 100)} {CPU_PERIOD_US}"


@dataclass(frozen=True)
class RestartSpec:
    policy: RestartPolicy = "on-failure"
    max_retries: int = 5  # consecutive failures before giving up (= N starts, not N+1)
    backoff_s: float = 1.0
    backoff_max_s: float = 60.0


@dataclass(frozen=True)
class ServiceDecl:
    id: str
    start: StartSpec
    name: str = ""
    # Values may reference ``${PORT_<name>}`` which the harness expands.
    env: Mapping[str, str] = field(default_factory=lambda: MappingProxyType({}))
    # port name -> requested port; 0 means "allocate for me".
    ports: Mapping[str, int] = field(default_factory=lambda: MappingProxyType({}))
    runtime: RuntimeSpec = RuntimeSpec()
    health: HealthSpec = HealthSpec()
    stop: StopSpec = StopSpec()
    limits: LimitsSpec = LimitsSpec()
    restart: RestartSpec = RestartSpec()

    def __post_init__(self) -> None:
        object.__setattr__(self, "env", MappingProxyType(dict(self.env)))
        object.__setattr__(self, "ports", MappingProxyType(dict(self.ports)))
        validate(self)


# --------------------------------------------------------------------------- parsing


def parse_size(text: str) -> int:
    m = _SIZE_RE.match(text.strip())
    if not m:
        raise ValueError(f"bad size {text!r}; expected e.g. 256M, 1G, 4096")
    mult = {"": 1, "K": 1 << 10, "M": 1 << 20, "G": 1 << 30, "T": 1 << 40}
    return int(m.group(1)) * mult[m.group(2).upper()]


def parse_percent(text: str) -> float:
    m = _PCT_RE.match(text.strip())
    if not m:
        raise ValueError(f"bad percent {text!r}; expected e.g. 50%")
    pct = float(m.group(1))
    if pct <= 0:
        raise ValueError("percent must be > 0")
    return pct


def _check_scalar(hint: Any, value: Any, path: str) -> None:
    """Best-effort runtime type check for str/int/float/bool/Optional/Literal hints."""
    origin = get_origin(hint)
    if origin is Union or (origin is not None and origin.__name__ == "UnionType"):
        options = get_args(hint)
        if value is None and type(None) in options:
            return
        for opt in options:
            if opt is type(None):
                continue
            try:
                _check_scalar(opt, value, path)
                return
            except DeclError:
                pass
        raise _err(path, f"expected one of {[getattr(o, '__name__', str(o)) for o in options]}")
    if origin is Literal:
        if value not in get_args(hint):
            raise _err(path, f"{value!r} not one of {list(get_args(hint))}")
        return
    if hint is float:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise _err(path, "expected a number")
        return
    if hint is int:
        if isinstance(value, bool) or not isinstance(value, int):
            raise _err(path, "expected an integer")
        return
    if hint is str:
        if not isinstance(value, str):
            raise _err(path, "expected a string")
        return
    if hint is bool:
        if not isinstance(value, bool):
            raise _err(path, "expected a boolean")
        return


def _build(cls: type, data: Any, path: str) -> Any:
    """Construct a frozen dataclass from a TOML table, rejecting unknown keys."""
    if not isinstance(data, dict):
        raise _err(path, f"expected a table, got {type(data).__name__}")
    known = {f.name: f for f in fields(cls)}
    unknown = sorted(set(data) - set(known))
    if unknown:
        raise _err(path, f"unknown keys {unknown}; allowed: {sorted(known)}")
    hints = get_type_hints(cls)
    kwargs: dict[str, Any] = {}
    for name in known:
        if name not in data:
            continue
        value = data[name]
        sub = f"{path}.{name}" if path else name
        if name in ("argv", "packages", "nix_packages"):
            if not isinstance(value, list) or not all(isinstance(x, str) for x in value):
                raise _err(sub, "expected a list of strings")
            kwargs[name] = tuple(value)
        else:
            _check_scalar(hints[name], value, sub)
            kwargs[name] = value
    try:
        return cls(**kwargs)
    except TypeError as e:  # missing required field
        raise _err(path or cls.__name__, str(e)) from None


_NESTED = {
    "start": StartSpec,
    "runtime": RuntimeSpec,
    "health": HealthSpec,
    "stop": StopSpec,
    "limits": LimitsSpec,
    "restart": RestartSpec,
}


def from_dict(data: Mapping[str, Any]) -> ServiceDecl:
    if not isinstance(data, Mapping):
        raise DeclError("declaration must be a table")
    allowed = {f.name for f in fields(ServiceDecl)}
    unknown = sorted(set(data) - allowed)
    if unknown:
        raise DeclError(f"unknown top-level keys {unknown}; allowed: {sorted(allowed)}")
    kwargs: dict[str, Any] = {}
    for key, value in data.items():
        if key in _NESTED:
            kwargs[key] = _build(_NESTED[key], value, key)
        else:
            kwargs[key] = value
    if "start" not in kwargs:
        raise DeclError("start: required table with argv")
    try:
        return ServiceDecl(**kwargs)
    except TypeError as e:
        raise DeclError(str(e)) from None


def loads(text: str) -> ServiceDecl:
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as e:
        raise DeclError(f"toml: {e}") from None
    return from_dict(data)


def load(path: str | Path) -> ServiceDecl:
    return loads(Path(path).read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- validation


def validate(d: ServiceDecl) -> None:  # noqa: C901 - one flat checklist is clearest
    if not isinstance(d.id, str) or not SERVICE_ID_RE.match(d.id):
        raise _err("id", f"{d.id!r} must match {SERVICE_ID_RE.pattern}")
    if not d.start.argv:
        raise _err("start.argv", "must not be empty")
    if any(not a for a in d.start.argv):
        raise _err("start.argv", "entries must be non-empty strings")
    if "\0" in d.start.workdir or not d.start.workdir:
        raise _err("start.workdir", "invalid path")
    if ".." in Path(d.start.workdir).parts:
        raise _err("start.workdir", "must not contain '..'")

    for k, v in d.env.items():
        if not ENV_NAME_RE.match(k):
            raise _err(f"env.{k}", "invalid environment variable name")
        if k in RESERVED_ENV or k.startswith(RESERVED_ENV_PREFIXES):
            raise _err(f"env.{k}", "reserved: set by the harness (PATH/HOME/AMS_*/PORT_*/...)")
        if not isinstance(v, str):
            raise _err(f"env.{k}", "value must be a string")
    for k, v in d.ports.items():
        if not PORT_NAME_RE.match(k):
            raise _err(f"ports.{k}", f"name must match {PORT_NAME_RE.pattern}")
        if not isinstance(v, int) or isinstance(v, bool):
            raise _err(f"ports.{k}", "must be an integer (0 = auto)")
        if v != 0 and not (MIN_PORT <= v <= MAX_PORT):
            raise _err(f"ports.{k}", f"must be 0 or in [{MIN_PORT}, {MAX_PORT}] (rootless)")
    for ref in sorted(port_refs(d)):
        if ref not in d.ports:
            raise _err("env", f"references ${{PORT_{ref}}} but ports.{ref} is not declared")

    rt = d.runtime
    kinds = ("none", "venv", "uv", "pnpm", "bun", "nix")
    if rt.kind not in kinds:
        raise _err("runtime.kind", f"{rt.kind!r} not one of {'/'.join(kinds)}")
    if rt.kind == "none" and (rt.requirements or rt.packages or rt.nix_packages):
        raise _err("runtime", "kind=none cannot declare packages/requirements")
    if rt.kind == "nix" and (rt.requirements or rt.packages):
        raise _err("runtime", "kind=nix uses nix_packages, not packages/requirements")
    if rt.kind != "nix" and rt.nix_packages:
        raise _err("runtime.nix_packages", "only valid with kind=nix")
    if rt.python is not None:
        if not rt.is_python:
            raise _err("runtime.python", "only valid with kind=venv or kind=uv")
        if not re.match(r"^\d+\.\d+$", rt.python):
            raise _err("runtime.python", "expected 'MAJOR.MINOR', e.g. '3.12'")
    if rt.node is not None:
        if not rt.is_node:
            raise _err("runtime.node", "only valid with kind=pnpm or kind=bun")
        if not re.match(r"^\d+(\.\d+){0,2}$", rt.node):
            raise _err("runtime.node", "expected a version like '22' or '22.12.0'")
    if rt.requirements is not None and not rt.is_python:
        raise _err("runtime.requirements", "only valid with kind=venv or kind=uv")
    if rt.sync:
        if rt.kind != "uv":
            raise _err("runtime.sync", "only valid with kind=uv")
        if rt.requirements is not None:
            raise _err("runtime.sync", "sync mode uses pyproject/uv.lock, not requirements")

    h = d.health
    if h.kind not in ("none", "tcp", "http", "log"):
        raise _err("health.kind", f"{h.kind!r} not one of none/tcp/http/log")
    if h.kind in ("tcp", "http"):
        if h.port is None:
            raise _err("health.port", f"required for kind={h.kind}")
        if h.port not in d.ports:
            raise _err("health.port", f"{h.port!r} is not declared in ports")
    if h.kind == "log":
        if not h.pattern:
            raise _err("health.pattern", "required for kind=log")
        try:
            re.compile(h.pattern)
        except re.error as e:
            raise _err("health.pattern", f"invalid regex: {e}") from None
    for fname in ("interval_s", "timeout_s", "start_period_s"):
        if getattr(h, fname) < 0:
            raise _err(f"health.{fname}", "must be >= 0")

    try:
        _ = d.stop.signum
    except AttributeError:
        raise _err("stop.signal", f"unknown signal {d.stop.signal!r}") from None
    if not d.stop.signal.startswith("SIG"):
        raise _err("stop.signal", "use the SIG* name, e.g. SIGTERM")
    if d.stop.timeout_s <= 0:
        raise _err("stop.timeout_s", "must be > 0")

    lim = d.limits
    try:
        _ = lim.memory_max_bytes
    except ValueError as e:
        raise _err("limits.memory_max", str(e)) from None
    try:
        _ = lim.cpu_max_value
    except ValueError as e:
        raise _err("limits.cpu_max", str(e)) from None
    if lim.pids_max is not None and lim.pids_max < 1:
        raise _err("limits.pids_max", "must be >= 1")

    r = d.restart
    if r.policy not in ("always", "on-failure", "never"):
        raise _err("restart.policy", f"{r.policy!r} not one of always/on-failure/never")
    if r.max_retries < 0 or r.backoff_s < 0 or r.backoff_max_s < r.backoff_s:
        raise _err("restart", "max_retries>=0, backoff_s>=0, backoff_max_s>=backoff_s")


_PORT_REF_RE = re.compile(r"\$\{PORT_([a-z][a-z0-9_]*)\}")


def port_refs(d: ServiceDecl) -> set[str]:
    """Port names referenced as ``${PORT_<name>}`` in env values or argv."""
    refs: set[str] = set()
    for text in (*d.env.values(), *d.start.argv):
        refs.update(_PORT_REF_RE.findall(text))
    return refs


def expand_ports(text: str, ports: Mapping[str, int]) -> str:
    def sub(m: re.Match[str]) -> str:
        name = m.group(1)
        if name not in ports:
            raise KeyError(f"port {name!r} not allocated")
        return str(ports[name])

    return _PORT_REF_RE.sub(sub, text)
